SCC-4022 : Node20
NYPL/node-nypl-data-api-client pull request #25
Opened 2024-05-01 20:12 UTC by nonword

Update app to use Node20:
 - Update/replace many packages
 - Use native `fetch`
 - Improvements to tests, including assertions around what http calls are triggered by client calls
 - Improved README
 - Added missing client & CLI support for PUT
 - Much linting modernization

Have also, prior to creating this PR:
 - transferred this repo from org:NYPL-discovery to org:NYPL
 - renamed `master` to `main`

This will be a v2.0 release.

https://jira.nypl.org/browse/SCC-4042

2024-05-06 16:45 UTC, charmingduchess requested changes

2024-05-06 16:45 UTC, charmingduchess commented on lib/client.js
This is an overall note regarding Promises. In my mind, the async/await pattern is there to try and remove Promises from the conversation. Returned values from async methods are [automatically wrapped in promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function#Return_value), so I think it would makes sense to omit the explicit returning of Promises in this repo. 

For example, I replaced `return Promise.reject(new RequestError(...)`  in `_doHtttpRequest` with `throw new RequestError(...)` on my local, and the tests checking for a promise rejection still pass as expected.

2024-05-06 16:45 UTC, charmingduchess commented on test/patch-test.js
> +      const call = client.patch('hold-requests/1234', JSON.stringify(holdRequestPatch), { json: false })
This might be clearer as 
```
const call = await client.patch('hold-requests/1234')
expect(call).to.be.a('object')
```
unless you already tried that and it wasn't working for some reason?

2024-05-06 19:01 UTC, nonword commented on test/patch-test.js
> +      const call = client.patch('hold-requests/1234', JSON.stringify(holdRequestPatch), { json: false })
That is clearer to read in this case - because the call resolves, allowing us to `await`. I think there's still value in using the `chai-as-promised` dsl for rejections (because there's no similarly concise way to "await" a rejection). Given that we're bound to use `chai-as-promised` hooks like `.be.rejectedWith` for testing error conditions, do you think I should migrate the non-error tests off of `chai-as-promised` hooks like `.eventually`?

2024-05-06 19:03 UTC, nonword commented on lib/client.js
Great point! I'm still definitely Promise-forward when I don't need to be. Updated. Thanks for the close read

2024-05-07 18:39 UTC, charmingduchess commented on test/patch-test.js
> +      const call = client.patch('hold-requests/1234', JSON.stringify(holdRequestPatch), { json: false })
Hmm good point about the rejections. I'm not *so* opposed to the `chai-as-promised` hooks, but it would be nice to remove the dependency. I found this pattern on stack overflow:
`rejects` and `doesNotReject` is an import from `'assert'`. 
eg:
```
 it('should fail if supplied body is plaintext', async () => {
      await rejects(client.post(`schemas/${testSchema.name}`, JSON.stringify(testSchema)))
    })

    // A null/empty body should be accepted as valid if options.json===true
    it('should succeed if supplied body is empty', async () => {
      await doesNotReject(client.post(`schemas/${testSchema.name}`))
    })
```
If you like the look of that, then feel free to incorporate.

2024-05-08 18:29 UTC, nonword commented on test/patch-test.js
> +      const call = client.patch('hold-requests/1234', JSON.stringify(holdRequestPatch), { json: false })
Good find. I've updated to remove `chai-as-promised`. `assert` seems to work roughly the same.

2024-05-10 14:33 UTC, charmingduchess approved these changes
`expect(review).to.eventually.be("approved")`

2024-05-10 15:06 UTC, merged